"""add_all_tables

Revision ID: 2160b46bd32f
Revises: 
Create Date: 2026-05-18 23:32:06.351601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2160b46bd32f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderation_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('content', sa.String(length=2000), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('action_taken', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_flags_content_hash'), 'moderation_flags', ['content_hash'], unique=False)
    op.create_index(op.f('ix_moderation_flags_correlation_id'), 'moderation_flags', ['correlation_id'], unique=False)
    op.create_table('expert_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('expertise_area', sa.String(length=50), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expert_conversations_correlation_id'), 'expert_conversations', ['correlation_id'], unique=False)
    op.create_table('learning_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.Column('weak_criteria', sa.JSON(), nullable=False),
    sa.Column('recommended_path', sa.JSON(), nullable=False),
    sa.Column('total_hours', sa.Integer(), nullable=False),
    sa.Column('tip', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_recommendations_correlation_id'), 'learning_recommendations', ['correlation_id'], unique=False)
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.Column('lesson_content_hash', sa.String(length=64), nullable=False),
    sa.Column('num_questions', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('lesson_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizzes_correlation_id'), 'quizzes', ['correlation_id'], unique=False)
    op.create_table('scoring_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=2), nullable=False),
    sa.Column('criteria_scores', sa.JSON(), nullable=False),
    sa.Column('weak_criteria', sa.JSON(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoring_history_correlation_id'), 'scoring_history', ['correlation_id'], unique=False)
    op.create_table('llm_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('service_name', sa.String(length=50), nullable=False),
    sa.Column('request_data', sa.String(length=2000), nullable=True),
    sa.Column('response_data', sa.String(length=2000), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_usage_logs_correlation_id'), 'llm_usage_logs', ['correlation_id'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('service_name', sa.String(length=50), nullable=False),
    sa.Column('request_data', sa.String(length=2000), nullable=True),
    sa.Column('response_data', sa.String(length=2000), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_logs_correlation_id'), 'usage_logs', ['correlation_id'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'role')
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_usage_logs_correlation_id'), table_name='usage_logs')
    op.drop_table('usage_logs')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_llm_usage_logs_correlation_id'), table_name='llm_usage_logs')
    op.drop_table('llm_usage_logs')
    op.drop_index(op.f('ix_scoring_history_correlation_id'), table_name='scoring_history')
    op.drop_table('scoring_history')
    op.drop_index(op.f('ix_quizzes_correlation_id'), table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_index(op.f('ix_learning_recommendations_correlation_id'), table_name='learning_recommendations')
    op.drop_table('learning_recommendations')
    op.drop_index(op.f('ix_expert_conversations_correlation_id'), table_name='expert_conversations')
    op.drop_table('expert_conversations')
    op.drop_index(op.f('ix_moderation_flags_correlation_id'), table_name='moderation_flags')
    op.drop_index(op.f('ix_moderation_flags_content_hash'), table_name='moderation_flags')
    op.drop_table('moderation_flags')
    # ### end Alembic commands ###
