"""add_suggestion_history_table

Revision ID: 818694491d15
Revises: 4889b48ba290
Create Date: 2026-05-21 21:38:59.796248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '818694491d15'
down_revision: Union[str, None] = '4889b48ba290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggestion_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.Column('anonymized_prompt', sa.Text(), nullable=False),
    sa.Column('weak_criteria', sa.JSON(), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggestion_history_correlation_id'), 'suggestion_history', ['correlation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suggestion_history_correlation_id'), table_name='suggestion_history')
    op.drop_table('suggestion_history')
    # ### end Alembic commands ###
