"""add user_id to moderation_flags

Revision ID: 894320c402c3
Revises: cceabc296805
Create Date: 2026-05-21 17:58:17.576499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '894320c402c3'
down_revision: Union[str, None] = 'cceabc296805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moderation_flags', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'moderation_flags', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'moderation_flags', type_='foreignkey')
    op.drop_column('moderation_flags', 'user_id')
    # ### end Alembic commands ###
