"""update_llm_usage_logs_fields

Revision ID: 9eb0ab0f15f7
Revises: 818694491d15
Create Date: 2026-05-21 22:00:32.886981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eb0ab0f15f7'
down_revision: Union[str, None] = '818694491d15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_usage_logs', sa.Column('model_used', sa.String(length=50), nullable=False))
    op.add_column('llm_usage_logs', sa.Column('total_tokens', sa.Integer(), nullable=False))
    op.add_column('llm_usage_logs', sa.Column('estimated_cost', sa.Float(), nullable=False))
    op.add_column('llm_usage_logs', sa.Column('cost_per_1k_tokens', sa.Float(), nullable=False))
    op.add_column('llm_usage_logs', sa.Column('time_to_first_token_ms', sa.Integer(), nullable=True))
    op.add_column('llm_usage_logs', sa.Column('request_preview', sa.String(length=500), nullable=True))
    op.add_column('llm_usage_logs', sa.Column('response_preview', sa.String(length=500), nullable=True))
    op.alter_column('llm_usage_logs', 'error_message',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('llm_usage_logs', 'request_data')
    op.drop_column('llm_usage_logs', 'response_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_usage_logs', sa.Column('response_data', sa.VARCHAR(length=2000), autoincrement=False, nullable=True))
    op.add_column('llm_usage_logs', sa.Column('request_data', sa.VARCHAR(length=2000), autoincrement=False, nullable=True))
    op.alter_column('llm_usage_logs', 'error_message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('llm_usage_logs', 'response_preview')
    op.drop_column('llm_usage_logs', 'request_preview')
    op.drop_column('llm_usage_logs', 'time_to_first_token_ms')
    op.drop_column('llm_usage_logs', 'cost_per_1k_tokens')
    op.drop_column('llm_usage_logs', 'estimated_cost')
    op.drop_column('llm_usage_logs', 'total_tokens')
    op.drop_column('llm_usage_logs', 'model_used')
    # ### end Alembic commands ###
